fix(componentheader): fix stage null check for component header when …
hey-car/heycar-uikit pull request #73
Opened 2022-09-02 13:04 UTC by esraltintas

…status component is used

Fix stage null check for component header when status component is used

## Pull Request

### Description

Describe your changes (or add ticket description) and add relevant screenshots

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change

### How do I test this

- Add steps to test
- in bullet point format
- preferably you can add link to the storybook build in the PR

## Checklist

### Did you remember to take care of the following?

- [ ] `npm i` – for new NPM dependencies.
- [ ] `npm run lint` - to check for linting issues
- [ ] `npm run test` - to run unit tests
- [ ] `npm run test:screenshots` - to run snapshot tests

### New Feature / Bug Fix

- [ ] Run unit tests to ensure all existing tests are still passing.
- [ ] Add new passing unit tests to cover the code introduced by your pr.

Thanks for contributing!

2022-09-02 13:59 UTC, derek-heycar requested changes

2022-09-02 13:59 UTC, derek-heycar commented on .storybook/blocks/ComponentHeader/ComponentHeader.tsx
> +      {stage != null && stage !== undefined && <Status stage={stage} />}
I guess too many checks.
Could you consider `isInteger` or set `default value` fix ways?

2022-09-05 06:49 UTC, hcafaq commented on .storybook/blocks/ComponentHeader/ComponentHeader.tsx
>      <div className={styles.component}>
I see `children` and `npmPackage` two unused props in this component and I feel they could be removed. Though it is not in scope of this PR so I don't feel strongly about this comment, you can use your judgement and decide on this. 
And I would suggest using default value for stage as Oleks suggested.

2022-09-09 12:21 UTC, merged

2022-09-09 12:28 UTC, derek-heycar commented
:tada: This PR is included in version 1.14.2 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@heycar-uikit/core/v/1.14.2)
- [GitHub release](https://github.com/hey-car/heycar-uikit/releases/tag/v1.14.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: