Feat/hey UI 168 screenshot updates
hey-car/heycar-uikit pull request #90
Opened 2022-10-04 12:51 UTC by esraltintas

## Pull Request

### Description

<img width="748" alt="Screenshot 2022-09-15 at 15 12 51" src="https://user-images.githubusercontent.com/1616251/193823661-fa5e355a-03b5-4c33-a732-29e81917d139.png">
 
Even we pass “children“ prop in our screenshot tests, all screenshots are using default parameter what we set in component stories

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change

### How do I test this

- Add steps to test
- in bullet point format
- preferably you can add link to the storybook build in the PR

## Checklist

### Did you remember to take care of the following?

- [x] `npm i` – for new NPM dependencies.
- [x] `npm run lint` - to check for linting issues
- [x] `npm run test` - to run unit tests
- [x] `npm run test:sh:docker` - to run screenshot tests, [detail instruction](https://hey-car.github.io/heycar-uikit/main/?path=/docs/guidelines-screenshot-testing--page)

### New Feature / Bug Fix

- [x] Run unit tests to ensure all existing tests are still passing.
- [] Add new passing unit tests to cover the code introduced by your pr.

Thanks for contributing!

2022-10-04 14:13 UTC, heyabinanto approved these changes

2022-10-04 19:21 UTC, hcafaq requested changes

2022-10-04 19:21 UTC, hcafaq commented on packages/button/src/docs/Component.stories.mdx
> +      type: { name: 'string', required: false },
why are we setting type of children as string here? isn't that always ReactNode in our components? 

`children?: React.ReactNode;
`
https://github.com/hey-car/hey-ui/blob/08798f872d1bc2a4f906ff721706568430414cc7/packages/icons/src/SvgIcon.types.tsx#L7

2022-10-05 11:20 UTC, hcafaq approved these changes

2022-10-05 11:21 UTC, merged

2022-10-05 11:29 UTC, derek-heycar commented
:tada: This PR is included in version 2.0.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@heycar-uikit/core/v/2.0.1)
- [GitHub release](https://github.com/hey-car/heycar-uikit/releases/tag/v2.0.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: