feat(tabs): add focus state on tabs in storybook
hey-car/heycar-uikit pull request #94
Opened 2022-10-06 12:18 UTC by esraltintas

add focus state on tabs in storybook

## Pull Request

### Description
<img width="556" alt="Screenshot 2022-09-07 at 11 08 02" src="https://user-images.githubusercontent.com/1616251/194310408-487ea7ab-7fb0-4db4-9471-818e2e40c774.png">

For accessibility storybook tabs should have a pressed state

The storybook tabs currently have a hover state, but need a focus state to give feedback to keyboard users so they can understand where they are in the page.

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation change

### How do I test this

- Add steps to test
- in bullet point format
- preferably you can add link to the storybook build in the PR

## Checklist

### Did you remember to take care of the following?

- [x] `npm i` – for new NPM dependencies.
- [x] `npm run lint` - to check for linting issues
- [x] `npm run test` - to run unit tests
- [x] `npm run test:sh:docker` - to run screenshot tests, [detail instruction](https://hey-car.github.io/heycar-uikit/main/?path=/docs/guidelines-screenshot-testing--page)

### New Feature / Bug Fix

- [x] Run unit tests to ensure all existing tests are still passing.
- [ ] Add new passing unit tests to cover the code introduced by your pr.

Thanks for contributing!

2022-10-06 13:24 UTC, heyabinanto approved these changes

2022-10-06 20:15 UTC, hcafaq approved these changes

2022-10-10 09:26 UTC, derek-heycar requested changes
Thanks for fixing it.
Just the two notices.
1. The similar problem as in the prev PR with the switcher component. There is no possibility to change state tabs by keys.
2. And the strange view of the active border (on screenshot)

<img width="392" alt="Screenshot 2022-10-10 at 11 25 56" src="https://user-images.githubusercontent.com/89923576/194835680-27791b51-4e67-4cf2-8e73-b41405d7e854.png">

2022-11-01 15:34 UTC, merged

2022-11-01 15:45 UTC, derek-heycar commented
:tada: This PR is included in version 2.10.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@heycar-uikit/core/v/2.10.0)
- [GitHub release](https://github.com/hey-car/heycar-uikit/releases/tag/v2.10.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: